### ISSUE TITLE
`No module named 'numpy'` running benchmark

### ISSUE THREAD

**Issue by vadi2** [turboderp/exllama#143]
I created a brand new conda environment on Ubuntu 22.04, but the benchmark isn't able to run:

```
conda create -n exllama python=3.10
Collecting package metadata (current_repodata.json): done
Solving environment: done
// ...

(base) vadi@barbar:~/Programs/exllama$ conda activate exllama
(exllama) vadi@barbar:~/Programs/exllama$ pip install -r requirements.txt
Collecting torch>=2.0.1 (from -r requirements.txt (line 1))
  Downloading torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 7.3 MB/s eta 0:00:00
Collecting safetensors==0.3.1 (from -r requirements.txt (line 2))
  Using cached safetensors-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting sentencepiece>=0.1.97 (from -r requirements.txt (line 3))
  Using cached sentencepiece-0.1.99-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting ninja==1.11.1 (from -r requirements.txt (line 4))
  Using cached ninja-1.11.1-py2.py3-none-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (145 kB)
Collecting filelock (from torch>=2.0.1->-r requirements.txt (line 1))
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting typing-extensions (from torch>=2.0.1->-r requirements.txt (line 1))
  Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Collecting sympy (from torch>=2.0.1->-r requirements.txt (line 1))
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting networkx (from torch>=2.0.1->-r requirements.txt (line 1))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 11.0 MB/s eta 0:00:00
Collecting nvidia-cuda-nvrtc-cu11==11.7.99 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 24.4 MB/s eta 0:00:00
Collecting nvidia-cuda-runtime-cu11==11.7.99 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 23.4 MB/s eta 0:00:00
Collecting nvidia-cuda-cupti-cu11==11.7.101 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 25.7 MB/s eta 0:00:00
Collecting nvidia-cudnn-cu11==8.5.0.96 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 7.1 MB/s eta 0:00:00
Collecting nvidia-cublas-cu11==11.10.3.66 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 11.2 MB/s eta 0:00:00
Collecting nvidia-cufft-cu11==10.9.0.58 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 14.8 MB/s eta 0:00:00
Collecting nvidia-curand-cu11==10.2.10.91 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_curand_cu11-10.2.10.91-py3-none-manylinux1_x86_64.whl (54.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 19.7 MB/s eta 0:00:00
Collecting nvidia-cusolver-cu11==11.4.0.1 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cusolver_cu11-11.4.0.1-2-py3-none-manylinux1_x86_64.whl (102.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 18.0 MB/s eta 0:00:00
Collecting nvidia-cusparse-cu11==11.7.4.91 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_cusparse_cu11-11.7.4.91-py3-none-manylinux1_x86_64.whl (173.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 15.3 MB/s eta 0:00:00
Collecting nvidia-nccl-cu11==2.14.3 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_nccl_cu11-2.14.3-py3-none-manylinux1_x86_64.whl (177.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 MB 12.4 MB/s eta 0:00:00
Collecting nvidia-nvtx-cu11==11.7.91 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading nvidia_nvtx_cu11-11.7.91-py3-none-manylinux1_x86_64.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.6/98.6 kB 8.2 MB/s eta 0:00:00
Collecting triton==2.0.0 (from torch>=2.0.1->-r requirements.txt (line 1))
  Downloading triton-2.0.0-1-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (63.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 MB 15.3 MB/s eta 0:00:00
Requirement already satisfied: setuptools in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=2.0.1->-r requirements.txt (line 1)) (67.8.0)
Requirement already satisfied: wheel in /home/vadi/Programs/miniconda3/envs/exllama/lib/python3.10/site-packages (from nvidia-cublas-cu11==11.10.3.66->torch>=2.0.1->-r requirements.txt (line 1)) (0.38.4)
Collecting cmake (from triton==2.0.0->torch>=2.0.1->-r requirements.txt (line 1))
  Using cached cmake-3.26.4-py2.py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (24.0 MB)
Collecting lit (from triton==2.0.0->torch>=2.0.1->-r requirements.txt (line 1))
  Using cached lit-16.0.6-py3-none-any.whl
Collecting MarkupSafe>=2.0 (from jinja2->torch>=2.0.1->-r requirements.txt (line 1))
  Using cached MarkupSafe-2.1.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mpmath>=0.19 (from sympy->torch>=2.0.1->-r requirements.txt (line 1))
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: sentencepiece, safetensors, ninja, mpmath, lit, cmake, typing-extensions, sympy, nvidia-nvtx-cu11, nvidia-nccl-cu11, nvidia-cusparse-cu11, nvidia-curand-cu11, nvidia-cufft-cu11, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cuda-cupti-cu11, nvidia-cublas-cu11, networkx, MarkupSafe, filelock, nvidia-cusolver-cu11, nvidia-cudnn-cu11, jinja2, triton, torch
Successfully installed MarkupSafe-2.1.3 cmake-3.26.4 filelock-3.12.2 jinja2-3.1.2 lit-16.0.6 mpmath-1.3.0 networkx-3.1 ninja-1.11.1 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-cupti-cu11-11.7.101 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 nvidia-cufft-cu11-10.9.0.58 nvidia-curand-cu11-10.2.10.91 nvidia-cusolver-cu11-11.4.0.1 nvidia-cusparse-cu11-11.7.4.91 nvidia-nccl-cu11-2.14.3 nvidia-nvtx-cu11-11.7.91 safetensors-0.3.1 sentencepiece-0.1.99 sympy-1.12 torch-2.0.1 triton-2.0.0 typing-extensions-4.7.1

(exllama) vadi@barbar:~/Programs/exllama$ python test_benchmark_inference.py -d /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GGML/ -p -ppl
/home/vadi/Programs/exllama/cuda_ext.py:82: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  none_tensor = torch.empty((1, 1), device = "meta")
 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 !! No files matching /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GGML/*.safetensors
```

What can I do to fix?

**Comment by vadi2** [comment]
Same issue running the webui:

```
$ python webui/app.py -d /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GGML/
/home/vadi/Programs/exllama/cuda_ext.py:82: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  none_tensor = torch.empty((1, 1), device = "meta")
 !! No files matching /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GGML/*.safetensors
```

I obtained the models from https://huggingface.co/TheBloke/wizard-vicuna-13B-SuperHOT-8K-GGML.

**Comment by turboderp** [comment]
`numpy` shouldn't be used anywhere, so I'm not sure why you're getting the warning. You can try installing it with `pip install numpy`, although it shouldn't make a difference. The error at the end has nothing to do with `numpy`, though. You're trying to use a GGML model. Get the GPTQ version instead.

**Comment by vadi2** [comment]
Doh. Thanks, that worked!

```
(exllama) vadi@barbar:~/Programs/exllama$ python test_benchmark_inference.py -d /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GPTQ/ -p -ppl
/home/vadi/Programs/exllama/cuda_ext.py:82: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  none_tensor = torch.empty((1, 1), device = "meta")
 -- Perplexity:
 -- - Dataset: datasets/wikitext2_val_sample.jsonl
 -- - Chunks: 100
 -- - Chunk size: 2048 -> 2048
 -- - Chunk overlap: 0
 -- - Min. chunk size: 50
 -- - Key: text
 -- Tokenizer: /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GPTQ/tokenizer.model
 -- Model config: /home/vadi/Programs/wizard-vicuna-13B-SuperHOT-8K-GPTQ/config.json
```
